### ISSUE TITLE
Authorization Failed (Invalid Token)

### ISSUE THREAD

**Issue by Pyperdok** [Nexure/DBD-API#3]
I am trying to log in via node js using the steam-user library to generate a ticket (get Auth Session Ticket method). After generating, I try to send a POST request to their backend with the ticket and the request body that you use, but I get an error - Invalid Token

	client.gamesPlayed(381210);

	client.getAuthSessionTicket(381210, function (err, ticket) {
		
		let auth_session_ticket = ticket;
		auth_session_ticket = auth_session_ticket.toString('hex');
		auth_session_ticket = auth_session_ticket.toUpperCase();
		console.log(auth_session_ticket);
		xhr.open('POST', 'https://latest.live.dbd.bhvronline.com/api/v1/auth/provider/steam/login?token=' + auth_session_ticket, false);
		xhr.setRequestHeader('Content-Type', 'application/json');

		let body = {"clientData":{"consentId":"2"}};
		xhr.send(JSON.stringify(body));

		console.log(xhr.responseText); // Invalid Ticket
	});

**Comment by Pyperdok** [comment]
Maybe it works for you, because steamworks starts the game, and I just imitate the launch (game Played method)

**Comment by Nexure** [comment]
Are you using the node-steam-user library? I've tried using the library and the session ticket it generates is not correct, and thus does not work with DBD's api's since all they do is call [AuthenticateUserTicket](https://partner.steamgames.com/doc/webapi/ISteamUserAuth#AuthenticateUserTicket) on steams backend, and generate a session if it is correct.

**Comment by Pyperdok** [comment]
And call [AuthenticateUserTicket](https://partner.steamgames.com/doc/webapi/ISteamUserAuth#AuthenticateUserTicket) is not enough for a ticket worked with dbd api?
Or the structure of the ticket generated by (get auth session ticket) incorrect/outdated?

**Comment by Pyperdok** [comment]
And for 1 year of using their api you get banned?

**Comment by Nexure** [comment]
I've tested its seems to be correct, though something the library does makes it not verify correctly or something. I'm unsure, because I spoke to the creator of the a [DBD stats website](https://dbd.onteh.net.au/), and he generates the token using near enough the same structure, but with different data, though you can find a thread on his forum with someone asking about the token he generates [here](https://dev.doctormckay.com/topic/2163-steam-returning-invalid-ticket-for-getauthsessionticket/).

With your other question, the account I use with the API has not been banned, so I guess its safe to use, though I'd still recommend using an alt as fakes you playing the game.
